export interface Scale {
  name: string;
  steps: { step: number; className: string }[];
}

export const palette: Scale[] = [
  {
    name: "brand-navy",
    steps: [
      { step: 50, className: "bg-brand-navy-50" },
      { step: 100, className: "bg-brand-navy-100" },
      { step: 200, className: "bg-brand-navy-200" },
      { step: 300, className: "bg-brand-navy-300" },
      { step: 400, className: "bg-brand-navy-400" },
      { step: 500, className: "bg-brand-navy-500" },
      { step: 600, className: "bg-brand-navy-600" },
      { step: 700, className: "bg-brand-navy-700" },
      { step: 800, className: "bg-brand-navy-800" },
      { step: 900, className: "bg-brand-navy-900" },
      { step: 950, className: "bg-brand-navy-950" },
    ],
  },
  {
    name: "brand-teal",
    steps: [
      { step: 50, className: "bg-brand-teal-50" },
      { step: 100, className: "bg-brand-teal-100" },
      { step: 200, className: "bg-brand-teal-200" },
      { step: 300, className: "bg-brand-teal-300" },
      { step: 400, className: "bg-brand-teal-400" },
      { step: 500, className: "bg-brand-teal-500" },
      { step: 600, className: "bg-brand-teal-600" },
      { step: 700, className: "bg-brand-teal-700" },
      { step: 800, className: "bg-brand-teal-800" },
      { step: 900, className: "bg-brand-teal-900" },
      { step: 950, className: "bg-brand-teal-950" },
    ],
  },
  {
    name: "neutral",
    steps: [
      { step: 50, className: "bg-neutral-50" },
      { step: 100, className: "bg-neutral-100" },
      { step: 200, className: "bg-neutral-200" },
      { step: 300, className: "bg-neutral-300" },
      { step: 400, className: "bg-neutral-400" },
      { step: 500, className: "bg-neutral-500" },
      { step: 600, className: "bg-neutral-600" },
      { step: 700, className: "bg-neutral-700" },
      { step: 800, className: "bg-neutral-800" },
      { step: 900, className: "bg-neutral-900" },
      { step: 950, className: "bg-neutral-950" },
    ],
  },
  {
    name: "success",
    steps: [
      { step: 50, className: "bg-success-50" },
      { step: 100, className: "bg-success-100" },
      { step: 200, className: "bg-success-200" },
      { step: 300, className: "bg-success-300" },
      { step: 400, className: "bg-success-400" },
      { step: 500, className: "bg-success-500" },
      { step: 600, className: "bg-success-600" },
      { step: 700, className: "bg-success-700" },
      { step: 800, className: "bg-success-800" },
      { step: 900, className: "bg-success-900" },
      { step: 950, className: "bg-success-950" },
    ],
  },
  {
    name: "warning",
    steps: [
      { step: 50, className: "bg-warning-50" },
      { step: 100, className: "bg-warning-100" },
      { step: 200, className: "bg-warning-200" },
      { step: 300, className: "bg-warning-300" },
      { step: 400, className: "bg-warning-400" },
      { step: 500, className: "bg-warning-500" },
      { step: 600, className: "bg-warning-600" },
      { step: 700, className: "bg-warning-700" },
      { step: 800, className: "bg-warning-800" },
      { step: 900, className: "bg-warning-900" },
      { step: 950, className: "bg-warning-950" },
    ],
  },
  {
    name: "error",
    steps: [
      { step: 50, className: "bg-error-50" },
      { step: 100, className: "bg-error-100" },
      { step: 200, className: "bg-error-200" },
      { step: 300, className: "bg-error-300" },
      { step: 400, className: "bg-error-400" },
      { step: 500, className: "bg-error-500" },
      { step: 600, className: "bg-error-600" },
      { step: 700, className: "bg-error-700" },
      { step: 800, className: "bg-error-800" },
      { step: 900, className: "bg-error-900" },
      { step: 950, className: "bg-error-950" },
    ],
  },
  {
    name: "info",
    steps: [
      { step: 50, className: "bg-info-50" },
      { step: 100, className: "bg-info-100" },
      { step: 200, className: "bg-info-200" },
      { step: 300, className: "bg-info-300" },
      { step: 400, className: "bg-info-400" },
      { step: 500, className: "bg-info-500" },
      { step: 600, className: "bg-info-600" },
      { step: 700, className: "bg-info-700" },
      { step: 800, className: "bg-info-800" },
      { step: 900, className: "bg-info-900" },
      { step: 950, className: "bg-info-950" },
    ],
  },
];

export const semanticSwatches: { name: string; className: string }[] = [
  { name: "background", className: "bg-background" },
  { name: "foreground", className: "bg-foreground" },
  { name: "card", className: "bg-card" },
  { name: "primary", className: "bg-primary" },
  { name: "secondary", className: "bg-secondary" },
  { name: "muted", className: "bg-muted" },
  { name: "accent", className: "bg-accent" },
  { name: "destructive", className: "bg-destructive" },
  { name: "border", className: "bg-border" },
  { name: "ring", className: "bg-ring" },
];
